include .env

TEST: 
	forge test --rpc-url $(SEPOLIA_RPC_URL) -vvvv

ANVIL-TEST: 
	forge test --fork-url $(ANVIL_FORK_URL) -vvvv

Test-Deploy-ANVIL:
		forge script script/DEPLOY_MYAA.s.sol:deployMyAA --fork-url $(ANVIL_FORK_URL) --account AnvilWallet 
